name: ItemExchanger
version: '${project.version}'
main: me.empty.itemexchanger.ItemExchanger
api-version: 1.20
commands:
  exchanger:
    description: Opens item exchange interface
    usage: /exchanger